site_name: ZHAW S4 — Prüfungszusammenfassung
site_description: Prüfungszusammenfassung ZHAW Applied Digital Life Science 4. Semester
site_author: Javier Martinez Alvarez

theme:
  name: material
  language: de
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Dunkelmodus
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Hellmodus
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.indexes
    - search.highlight
    - search.suggest
    - search.share
    - content.code.copy
    - toc.follow

plugins:
  - search:
      lang: de

markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html
  - toc:
      permalink: true

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Übersicht: index.md
  - NeuNe — Neural Networks: neune.md
  - OrgChem — Organische Chemie: orgchem.md
  - ISP — Image & Signal Processing: isp.md
  - MCS — Modellierung komplexer Systeme: mcs.md
  - DaS — Data and Society: das.md
  - DSV — Digital Storytelling & Visualisation: dsv.md
